### ISSUE TITLE
Not able to import any assets.

### ISSUE THREAD

**Issue by oschakravarthi** [xenko3d/xenko#495] opened 2019-08-10 09:57 UTC
Not able to import any 3d models except FBX. Game studio is not even showing any errors/warnings. Just keeps quite. I am using the latest version: 3.1.0.1-beta02-0635

Very unstable product.

**Comment by Bloodshoot111** [comment] 2019-08-10 10:01
Well I'm not an developer but comments like very unstable product are not for GitHub issues. Keep that for yourself or go to the Forums/Discord.

**Comment by xen2** [comment] 2019-08-14 10:34
@oschakravarthi Does installing latest Visual C++ x64 redist helps?
Here is the link: https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by xen2** [comment] 2019-08-14 11:27
Duplicate of #465. Will be part of next release.

**Closed by xen2** 2019-08-14 11:27 UTC
Labels: bug

**Comment by xen2** [comment] 2019-08-14 13:49
Should be fixed in latest beta (674)
