### ISSUE TITLE
CompilerApp error on build

### ISSUE THREAD

**Issue by SilentCLD** [xenko3d/xenko#519] opened 2019-09-25 20:21 UTC
**Release Type**: GitHub master

**Version**: 3f3158783ec94c9f4705e3afd50e671b05b2ed15

**Platform(s)**: Windows

**Describe the bug**
CompilerApp is failing to build causing game projects to not compile through Game Studio

**To Reproduce**
1. (Re)build source

**Expected behavior**
Building shouldn't produce any errors.

**Log and callstacks**
[xenko_callstack.txt](https://github.com/xenko3d/xenko/files/3654559/xenko_callstack.txt)

**Comment by profan** [comment] 2019-09-26 16:20
Running into this same error on 3.1.0.1 as well.

**Comment by fdrobidoux** [comment] 2019-09-29 22:47
I can confirm, I'm getting the exact same error.

**Comment by Eideren** [comment] 2019-10-18 16:24
Does this error still occur for you ? I can't reproduce it on branch master-3.1

**Comment by xen2** [comment] 2019-10-18 16:35
Should be fixed in latest master-3.1 with https://github.com/xenko3d/xenko/commit/297d239cc89ddee88d4cc52448336b35fa93080d

**Closed by xen2** 2019-10-18 16:35 UTC
Labels: bug

**Comment by SilentCLD** [comment] 2019-10-19 14:42
Yep can confirm successful building with master-3.1
