### ISSUE TITLE
Please, make a tutorial on how to create simple xenko project using only nuget(without installation of the xenko distribution)

### ISSUE THREAD

**Issue by rds1983** [xenko3d/xenko#315] opened 2019-01-08 21:47 UTC
Or maybe even better idea is to add custom template(s) to nuget, that could be installed through `dotnet new -i Xenko.Game.Template` and used through `dotnet new xenkogame`

**Comment by Kryptos-FR** [comment] 2019-01-08 22:47
The first thing that come to mind when I see an issue starting with "please make" or "please do" is to close it as invalid or off-topic.

You don't make demand to a project, especially one that is free. You contribute by reporting bug and or making suggestion.  Also there is an issue template for a reason.

**Comment by rds1983** [comment] 2019-01-08 22:51
I simply followed recommendation I got from gitter chat:
![image](https://user-images.githubusercontent.com/1057289/50863823-911a7180-13d2-11e9-91f6-36d8dde3dd5e.png)

**Comment by xen2** [comment] 2019-01-08 23:30
@Kryptos-FR That's fine, we want new community members to feel welcome.
A "please" doesn't strike me as bad, and it doesn't make the demand/issue any less valid (you can ignore it in your head and it's easy to edit the title).
Let's just focus on the actual substance rather than the form.

**Comment by xen2** [comment] 2019-01-08 23:32
@rds1983 On a more interesting front, this looks like a duplicate of #80 
Can you add your `dotnet new` suggestion there please?

**Closed by xen2** 2019-01-08 23:32 UTC

**Comment by Kryptos-FR** [comment] 2019-01-09 00:20
@xen2 I have been reminded countless time by my native-English coworkers that "please do" is a demand in English. And that it is sometimes considered obsequious and/or sarcastic, instead of being polite.

It also makes the title very long for no purposes.

/end rant

**Comment by Kryptos-FR** [comment] 2019-01-09 01:50
@rds1983 There is no need for "please" at all IMO. Use imperative mood, optionally with "Feature request: XXX"

For example:
* "Add an example (tutorial) using only nuget"
* "Feature request: Add an example (tutorial) using only nuget"

It is shorter and has all the relevant information. Details should be in the description. ;)

**Comment by Kryptos-FR** [comment] 2019-01-09 02:53
@rds1983 I couldn't quickly figure out how to make it work for a netcoreapp, but I managed to have a minimal project for net461 (see attachment: [Xnk.zip](https://github.com/xenko3d/xenko/files/2739186/Xnk.zip)). Hopefully it can get you started.

See how some libraries are optional (e.g. navigation or physics).

Then we can continue the discussion on the other issue (#80).
