### ISSUE TITLE
Bright Filter Post-processing effect visual artifacts

### ISSUE THREAD

**Issue by Leocesar3D** [xenko3d/xenko#330] opened 2019-01-19 10:50 UTC
Xenko 3.1.0.1-beta01-0359

Platform/hardware: Geforce Windows 10, GTX 1070, Nvidia driver version: 417.71

When I activate the Bright Filter Post-processing effect it generates render artifacts on editor or in build.

To Reproduce: Enable Bright Filter Post-processing effect

Expected behavior: 
![xenkoartifact](https://user-images.githubusercontent.com/46840152/51425735-2d105e00-1bc7-11e9-9e81-e9a3ccba6b4a.jpg)
![xenkoartifact2](https://user-images.githubusercontent.com/46840152/51425736-2d105e00-1bc7-11e9-8d01-dd49929b47ab.jpg)

Visual artifacts: black spots, streaks.

**Comment by Kryptos-FR** [comment] 2019-01-19 12:44
Possible duplicate of #325.

On a side-note, if possible follow the issue template.

**Comment by xen2** [comment] 2019-03-17 05:00
Closing as a duplicate of #325.

**Closed by xen2** 2019-03-17 05:00 UTC
Labels: bug
