### ISSUE TITLE
Launcher 3.0.0.6 to 3.1 Update error/fails

### ISSUE THREAD

**Issue by phatyh** [xenko3d/xenko#371] opened 2019-02-09 11:39 UTC
**Release Type**: Official Release/GitHub (please choose appropriate option)

**Version**: 3.1.0.1-beta01-0441

**Platform(s)**: Windows 10 Pro Build 1809

**Describe the bug**
Update fails to install

**To Reproduce**
1. Run Xenko Launcher
2.  Click download for Xenko 3.1 update

**Log and callstacks**
```
An error occurred while installing version 3.1.0.1-beta01-0441.
Failed to retrieve information about 'Humanizer.Core' from remote source 'https://api.nuget.org/v3-flatcontainer/humanizer.core/index.json'.
Unable to find package 'Xenko.Core.Assets.Quantum.3.1.0.1-beta01-0441'.
 at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d7.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()
```

**Comment by Kryptos-FR** [comment] 2019-02-09 12:55
The title of the issue is confusing as there is no such thing as an update from 3.0 to 3.1 in the launcher: both versions have their separate entry.

The actual issue seems to be a network/nuget failure. Try again and it should work.

On a side note, it is quite surprising to see an error related to the 'Humanizer.Core' package since I don't think we use that library.

**Comment by xen2** [comment] 2019-02-09 16:36
@Kryptos-FR We do indirectly :)
https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp.Features/2.10.0

I will close this as a duplicate of #310

**Closed by xen2** 2019-02-09 16:36 UTC
Labels: bug
