### ISSUE TITLE
Input.IsKeyPressed does not behave as intended.

### ISSUE THREAD

**Issue by justStand** [xenko3d/xenko#159] opened 2018-08-27 05:12 UTC
It seems to rely on the Windows keyboard "Repeat rate" setting.

If you hold a key down; whenever Windows will output the key, the input.iskeypressed will return true.

**Comment by Kryptos-FR** [comment] 2018-08-27 05:36
From what I can read in the code (https://github.com/xenko3d/xenko/blob/master/sources/engine/Xenko.Input/Windows/KeyboardWinforms.cs) it seems to rely on low-level Win32 API.

That said it is possible that the "Repeat rate" setting simulates up and down events which will explain what you described (I don't know much about that feature). Were that the case, I don't think there is much we can do (since it means it is affecting low-level Win32 API).

We need to investigate more...

**Comment by Eideren** [comment] 2018-08-31 15:30
@Kryptos-FR You were right; changing windows' keyboard repeat rate changes the rate at which it is repeated in-engine. 

Based on [this page](https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-syskeydown) we can see that the second to last bit on the LParam provides us a filter which would help us to ignore repeating messages. I added logging code to [InputSourceWinforms](https://github.com/xenko3d/xenko/blob/master/sources/engine/Xenko.Input/Windows/InputSourceWinforms.cs)'s HandleKeyDown / HandleKeyUp and here's the content of the lParam IntPtr casted to an int32 and converted to bit representation in the console : 
![inputissue](https://user-images.githubusercontent.com/5742236/44920307-de5d4700-ad3f-11e8-83df-4d204160667f.jpg)
As you can see on line 'A', the first down event for the key starts with a zeroed second bit, which, on the following event while holding the key, turns to one.

On line 'B' and 'C', you can see that the previous key was released and another one pressed but no up event occurred. We are actively sampling the API, It isn't interrupting with messages right ? If that's the case then this is just an editor side sample issue.
You can also see a variant of that issue crop up on line 'D' were the first down event wasn't caught but the following repeating events were.


I could push a fix for this since I already had a couple of other minor fix in other parts of the input system but just to be sure, can I safely filter out those repeated inputs based on what I found or am I forgetting something ? And is the issue shown on line B, C and D expected behavior ?

**Comment by xen2** [comment] 2018-09-02 11:56
I agree with your analysis, it shouldn't trigger `IsKeyPressed` multiple time if it's a single long keypress.
Would gladly accept a PR fix, thanks!

**Closed** 2018-09-25 05:00 UTC
Labels: bug

**Comment by justStand** [comment] 2018-09-25 15:54
A Console.Writeline made it through https://github.com/xenko3d/xenko/commit/7b2659b27a706e6f83d6a45ccab493a217255235#diff-d811585b0ddab8979281627eaf126832R144
