### ISSUE TITLE
Launcher 3.0.0.6 to 3.1 Update error/fails

### ISSUE THREAD

**Issue by Vhaldir** [xenko3d/xenko#295] opened 2018-12-23 20:09 UTC
**Release Type**: Official Release/GitHub (please choose appropriate option)

**Version**: 3.1

**Platform(s)**: Windows

**Describe the bug**
Update fails to install

**To Reproduce**
1. Run Xenko Launcher
2. Click download for Xenko 3.1 update

**Screenshots**
![image](https://user-images.githubusercontent.com/542734/50387202-9aee6600-06ab-11e9-82dd-b5a3d9eba78e.png)

**Comment by justStand** [comment] 2018-12-23 21:33
Having the same issue but with a shorter error.


`An error occurred while installing version 3.1.0.1-beta01-0313. Could not restore package Xenko.GameStudio at Xenko.Core.Packages.NugetStore.<InstallPackage>d50.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass550.<<Download>b_0>d.MoveNext()`

**Comment by Kryptos-FR** [comment] 2018-12-24 02:06
It looks like it could be a timeout issue in NuGet. Try again later, it worked for me after the 3rd try.

**Comment by Timurid** [comment] 2018-12-24 09:19
An error occurred while installing version 3.1.0.1-beta01-0313.
Unable to find package Xenko.Graphics.RenderDocPlugin with version (>= 3.1.0.1-beta01-0313)
•	Found 1 version(s) in Xenko [ Nearest version: 3.1.0.1-beta01 ]
•	Found 0 version(s) in Microsoft Visual Studio Offline Packages
•	Found 0 version(s) in Xenko Dev
•	Found 0 version(s) in nuget.org
Could not restore package Xenko.GameStudio at Xenko.Core.Packages.NugetStore.<InstallPackage>d50.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at Xenko.LauncherApp.ViewModels.PackageVersionViewModel.<>cDisplayClass550.<<Download>b_0>d.MoveNext()

**Comment by xen2** [comment] 2018-12-24 13:56
I think it is on nuget.org ends, not much I can do:
![image](https://user-images.githubusercontent.com/527565/50401073-1d237b00-07cf-11e9-9344-014b11962ed1.png)

**Comment by justStand** [comment] 2018-12-25 10:09
Seems to be working now.

**Comment by tebjan** [comment] 2018-12-25 23:20
confirmed, works here now too.

**Comment by xen2** [comment] 2018-12-26 06:58
Thanks for testing.
It also got verified on NuGet: https://www.nuget.org/packages/Xenko.Graphics.RenderDocPlugin
Closing!

**Closed by xen2** 2018-12-26 06:58 UTC
