### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by LowRhyan567** [xenko3d/xenko#392] opened 2019-02-23 22:29 UTC
Error type:

Failed to retrieve information about 'Microsoft.Win32.Registry' from remote source 'https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/index.json'.
Unable to find package 'System.ValueTuple.4.4.0'. at NuGet.Protocol.FindPackagesByIdNupkgDownloader.<GetNuspecReaderFromNupkgAsync>d6.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Protocol.HttpFileSystemBasedFindPackageByIdResource.<GetDependencyInfoAsync>d7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesCoreAsync>d22.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<>cDisplayClass21_0.<<GetDependenciesAsync>b0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.Commands.SourceRepositoryDependencyProvider.<GetDependenciesAsync>d21.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<CreateGraphItemAsync>d2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NuGet.DependencyResolver.ResolverUtility.<FindLibraryEntryAsync>d1.MoveNext()

**Comment by tebjan** [comment] 2019-02-25 13:48
seems to be a network issue, since this didn't happen on other machines. i would just try downloading again. close issue?

**Comment by xen2** [comment] 2019-03-08 13:19
Do you still have it?
If yes, can you give a try to this new `XenkoSetup.exe` installer?
https://teamcity.xenko.com/viewLog.html?buildId=4919&buildTypeId=Engine_Package_BuildLauncher&tab=artifacts&guest=1#%2Fbin%2Flauncher

**Comment by LowRhyan567** [comment] 2019-03-09 02:23
Ok, thx.

Em sex, 8 de mar de 2019 às 10:19, Virgile Bello <notifications@github.com>
escreveu:

**Comment by xen2** [comment] 2019-06-03 14:19
Duplicate of #310

**Closed by xen2** 2019-06-03 14:19 UTC
Labels: bug
