### ISSUE TITLE
xenko not completely removed from windows after uninstall

### ISSUE THREAD

**Issue by iperov** [xenko3d/xenko#162] opened 2018-08-27 14:41 UTC
I creating any new C# .NET project in VS2017 and I getting this error:
![devenv_2018-08-27_18-38-46](https://user-images.githubusercontent.com/8076202/44666002-713c6f80-aa28-11e8-9443-055751b1c6b5.jpg)

also these files exists in directories:

![explorer_2018-08-27_18-40-09](https://user-images.githubusercontent.com/8076202/44666070-a1840e00-aa28-11e8-8095-c84abae3a76e.jpg)

also a lot of registry keys which can be searched by "xenko" - not removed.

**can you please provide tool that will completely remove this shit and fix my system ?**

**Comment by Kryptos-FR** [comment] 2018-08-27 15:27
It is a **Visual Studio** plugin. So, it doesn't appear in "Program and features" but in Visual Studio "Extensions and features".

**Comment by iperov** [comment] 2018-08-27 15:29
fixed by reinstalling VS2018.

This plugin must be removed when I remove xenko, because it installed through xenko installer.

**Comment by xen2** [comment] 2018-09-25 11:54
Duplicate of recently opened #215. I'll keep the other one open.

**Closed by xen2** 2018-09-25 11:54 UTC
Labels: bug
