### ISSUE TITLE
Feature request: Add CI builds on GitHub (such as AppVeyor and Travis)

### ISSUE THREAD

**Issue by aaronfranke** [xenko3d/xenko#65] opened 2018-08-06 05:59 UTC
CI stands for Continuous Integration, it means that a service will automatically handle builds. This is useful for making sure that new commits don't break the engine. It's also extremely useful for testing if pull requests are compilable before developers even need to review them. For example:

* [AppVeyor](https://www.appveyor.com) is useful for automating Windows builds (Windows Server host).

* [Travis](https://travis-ci.org) is useful for automating Mac, Linux, Android, and iOS builds (Linux host).

**Comment by xen2** [comment] 2018-08-06 06:06
Duplicate of https://github.com/xenko3d/xenko/issues/46

**Closed by xen2** 2018-08-06 06:06 UTC
